<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="4" passed="3" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-08-04T21:12:30 IST" name="Suite" finished-at="2024-08-04T21:12:34 IST" duration-ms="4743">
    <groups>
    </groups>
    <test started-at="2024-08-04T21:12:30 IST" name="Test" finished-at="2024-08-04T21:12:34 IST" duration-ms="4743">
      <class name="api.testcases.UserTest">
        <test-method is-config="true" signature="setPayload()[pri:0, instance:api.testcases.UserTest@70ed52de]" started-at="2024-08-04T21:12:30 IST" name="setPayload" finished-at="2024-08-04T21:12:30 IST" duration-ms="448" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setPayload -->
        <test-method signature="testCreateUser()[pri:1, instance:api.testcases.UserTest@70ed52de]" started-at="2024-08-04T21:12:30 IST" name="testCreateUser" finished-at="2024-08-04T21:12:32 IST" duration-ms="2077" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCreateUser -->
        <test-method signature="testGetUser()[pri:2, instance:api.testcases.UserTest@70ed52de]" started-at="2024-08-04T21:12:32 IST" name="testGetUser" finished-at="2024-08-04T21:12:33 IST" duration-ms="674" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testGetUser -->
        <test-method signature="testUpdateUser()[pri:3, instance:api.testcases.UserTest@70ed52de]" started-at="2024-08-04T21:12:33 IST" name="testUpdateUser" finished-at="2024-08-04T21:12:34 IST" duration-ms="697" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Staus code should be 200 expected [400] but found [200]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Staus code should be 200 expected [400] but found [200]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1578)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:1419)
at org.testng.Assert.assertEquals(Assert.java:1383)
at api.testcases.UserTest.testUpdateUser(UserTest.java:71)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:686)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:992)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:614)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUpdateUser -->
        <test-method signature="testDeeleteUser()[pri:4, instance:api.testcases.UserTest@70ed52de]" started-at="2024-08-04T21:12:34 IST" name="testDeeleteUser" finished-at="2024-08-04T21:12:34 IST" duration-ms="639" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testDeeleteUser -->
      </class> <!-- api.testcases.UserTest -->
    </test> <!-- Test -->
  </suite> <!-- Suite -->
</testng-results>
